name: Manually Deploy to Heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bervProject/railway-deploy@0.0.6-alpha
        with:
          RAILWAY_TOKEN: ${{secrets.RAILWAY_TOKEN}}
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
        env:
          HD_CONFIG_FILE_URL: ${{secrets.CONFIG_FILE_URL}}
