name: Manually Deploy to Railway

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bervProject/railway-deploy@0.0.6-alpha
        with:
          RAILWAY_TOKEN: ${{secrets.RAILWAY_TOKEN}}
          using: 'docker'
          image: Dockerfile
        env:
          HD_CONFIG_FILE_URL: ${{secrets.CONFIG_FILE_URL}}
